version: '3.5'

volumes:
  postgres_user_volume:

services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready"]
    ports:
      - "5433:5432"
    networks:
      - user-network

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    env_file:
      - .env
    networks:
      - user-network

  user-service:
    restart: always
    build: .
    depends_on:
      - postgres
    ports:
      - "${GRPC_PORT:-5002}:${GRPC_PORT:-5002}"
      - "${HTTP_PORT:-8081}:${HTTP_PORT:-8081}"
      - "${SWAGGER_PORT:-8091}:${SWAGGER_PORT:-8091}"
    networks:
      - user-network

networks:
  user-network: